version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: 10_task
    environment:
      POSTGRES_USER: lesson
      POSTGRES_PASSWORD: lesson
      POSTGRES_DB: processingcenter
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d